[build]
target = "riscv32imc-unknown-none-elf"


[target.riscv32imc-unknown-none-elf]
linker = "ld.lld"
# adding linker requirements as needed by the riscv-rt crate
rustflags = [
    "-C", "link-arg=-L./src/ld/mine",
    "-C", "link-arg=-Tmemory.x",
    "-C", "link-arg=-Tdefmt.x", # needed to help store interned strings in the output object file
    "-C", "link-arg=-Tlink.x"
]
