[package]
name = "_0_simple_bare_metal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# esp-println = { version = "0.8.0", features = ["esp32c3"] }
riscv-rt = "0.12.2"
